import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F9FA', 
  },
  backgroundElements: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 0,
  },
  circle1: {
    position: 'absolute',
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'rgba(59, 130, 246, 0.05)',
    top: height * 0.1,
    right: -30,
  },
  circle2: {
    position: 'absolute',
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(16, 185, 129, 0.08)',
    top: height * 0.6,
    left: -20,
  },
  circle3: {
    position: 'absolute',
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: 'rgba(139, 92, 246, 0.06)',
    top: height * 0.3,
    left: width * 0.7,
  },
  rectangle1: {
    position: 'absolute',
    width: 100,
    height: 40,
    backgroundColor: 'rgba(245, 158, 11, 0.08)',
    borderRadius: 8,
    top: height * 0.8,
    right: width * 0.1,
    transform: [{ rotate: '15deg' }],
  },
  rectangle2: {
    position: 'absolute',
    width: 80,
    height: 30,
    backgroundColor: 'rgba(239, 68, 68, 0.09)',
    borderRadius: 6,
    top: height * 0.15,
    left: width * 0.1,
    transform: [{ rotate: '-10deg' }],
  },
  screenContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 30,
    paddingTop: 60,
    paddingBottom: 40,
    zIndex: 1,
  },
  logoContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 50,
  },
  logoSquare: {
    width: 60,
    height: 60,
    backgroundColor: '#000000',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  logoText: {
    fontSize: 24,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  widgetContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 40,
    width: '100%',
    height: 280,
  },
  scrollView: {
    width: '100%',
    height: 280,
  },
  slideContainer: {
    width: width,
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  widgetCard: {
    width: width * 0.75,
    maxWidth: 320,
    minWidth: 250,
    height: 200,
    backgroundColor: '#F3F4F6',
    borderRadius: 16,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    flexDirection: 'column',
  },
  widgetHeader: {
    marginBottom: 16,
  },
  widgetTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#000',
    textAlign: 'left',
  },
  // Todos widget styles
  todosContent: {
    flex: 1,
    gap: 12,
    justifyContent: 'space-between',
  },
  todoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  todoCheckbox: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#D1D5DB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  todoCheckmark: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#10B981',
  },
  todoText: {
    flex: 1,
    gap: 4,
  },
  todoLineLong: {
    height: 2,
    backgroundColor: '#D1D5DB',
    borderRadius: 1,
    width: '100%',
  },
  todoLineMedium: {
    height: 2,
    backgroundColor: '#D1D5DB',
    borderRadius: 1,
    width: '75%',
  },
  todoLineShort: {
    height: 2,
    backgroundColor: '#D1D5DB',
    borderRadius: 1,
    width: '50%',
  },
  // Calendar header styles
  calendarHeader: {
    backgroundColor: '#E5E7EB',
    borderRadius: 8,
    padding: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  calendarContent: {
    flex: 1,
    alignItems: 'center',
    gap: 16,
    paddingHorizontal: 10,
    justifyContent: 'space-between',
  },
  calendarDate: {
    fontSize: 48,
    fontWeight: '700',
    color: '#000',
  },
  daysRow: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  dayPill: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dayPillActive: {
    backgroundColor: '#3B82F6',
  },
  dayPillInactive: {
    backgroundColor: '#E5E7EB',
  },
  dayText: {
    fontSize: 12,
    fontWeight: '500',
    color: '#6B7280',
  },
  dayTextActive: {
    fontSize: 12,
    fontWeight: '500',
    color: '#FFFFFF',
  },
  // Projects widget styles
  projectsContent: {
    flex: 1,
    gap: 12,
    justifyContent: 'space-between',
  },
  projectItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 12,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  projectIcon: {
    width: 24,
    height: 24,
    borderRadius: 6,
    backgroundColor: '#E5E7EB',
  },
  projectText: {
    flex: 1,
    gap: 4,
  },
  projectLineShortDark: {
    height: 2,
    backgroundColor: '#000',
    borderRadius: 1,
    width: '30%',
  },
  projectLineMediumDark: {
    height: 2,
    backgroundColor: '#000',
    borderRadius: 1,
    width: '50%',
  },
  projectLineLong: {
    height: 2,
    backgroundColor: '#D1D5DB',
    borderRadius: 1,
    width: '100%',
  },
  projectLineShortLight: {
    height: 2,
    backgroundColor: '#D1D5DB',
    borderRadius: 1,
    width: '25%',
  },
  welcomeText: {
    fontSize: 28,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 8,
  },
  welcomeLine1: {
    color: '#000',
  },
  welcomeLine2: {
    color: '#3B82F6',
  },
  tagline: {
    fontSize: 16,
    color: '#6B7280',
    textAlign: 'center',
    marginBottom: 40,
    lineHeight: 24,
  },
  getStartedButton: {
    backgroundColor: '#000000',
    paddingHorizontal: 32,
    paddingVertical: 16,
    borderRadius: 12,
    marginBottom: 30,
  },
  getStartedText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
  paginationContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
  },
  paginationDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#D1D5DB',
  },
  paginationDotActive: {
    backgroundColor: '#3B82F6',
    width: 24,
  },
});

export default styles;

